rssLimit = 20
baseURL = "/"
languageCode = "en-us"
title = "apiercey.github.io"
themesDir = "themes"
theme = "hugo-winston-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = 'base16-snazzy'
paginate = 6
ignoreErrors = ["error-remote-getjson"]

[author]
	name = "Alexander Butt-Piercey"
	email = "alexander.piercey@gmail.com"

[markup]
  [markup.highlight]
    anchorLineNos = true
    lineNos = true
    lineNoStart = 1
    lineNumbersInTable = false
    hl_Lines = ''

    [markup.goldmark.renderer]
      unsafe = true


[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  google_analytics_id = "G-CX84WRHVTJ"
  twitter_handle = "@programincolour"
  showAuthorOnHomepage = true
  showAuthorOnPosts = false
  showPostsOnHomepage = false
  addFrame = false
  addDot = true
  hostName = "https://apiercey.github.io"

[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5

